#!/bin/bash

# Larger bash history (allow 32^3 entrie; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE=" *:ls;cd;cd -;pwd:exit:date:* --help: -h:ls *:ll"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X";
